language: java
script:
- mvn clean verify
- mvn package
deploy:
  skip_cleanup: true
  provider: releases
  file: target/releases/elasticsearch-http-basic-plugin.zip
  on:
    repo: Sessa93/elasticsearch-http-basic
    tags: true
    branch: master
